### PR TITLE
fix(tangle-dapp): Various bug fixes

### LINKED ISSUE #2799: [TASK] Update bridge asset list component
- Display token name along with token symbol for better clarity.
- If 0 balance, display just 0 instead of 0.000...

Note: Make sure it is applied to all pages (restake, bridge etc)

Image

### LINKED ISSUE #2804: [BUG] Unable to Bond & Nominate Validators on EVM
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently on Tangle EVM (both testnet and mainnet), when I click the `Nominate` button on the Nomination table, enter the required inputs, and confirm the transaction in my EVM wallet, the transaction appears successful with a notification confirming the nomination. However, upon checking the results, there are no bonded funds and no nomination recorded.

### Expected Behavior

Once the nomination transaction is confirmed on the EVM, users must ensure they are a nominator with the bonded function and that their nomination is recorded correctly. If the transaction fails, users will see a notification with an error message.

### Steps To Reproduce

1. Open the Tangle dApp locally or on the [development site](https://develop--tangle-dapp.netlify.app/).
2. Connect your **EVM wallet** (e.g., MetaMask).
3. Click the `Nominate` tab.
4. Scroll to the `Nominations` table and click the `Nominate` button. If the button is not visible, your current account is already a nominator; switch to another account with TNT available for nomination.
5. Enter the required information.
6. Click `Confirm` in the modal and your EVM wallet.
7. Wait for the success notification.
8. If nominations do not appear in the table after refreshing, check the [PolkadotJS Portal](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet-rpc.tangle.tools#/chainstate) by querying `staking.bonded`, `staking.nominator`, and `staking.ledger` using your converted Substrate address (convert your EVM address [here](https://docs.tangle.tools/resources/resources)).

### Screenshot

**_Nominate transaction execution from an EVM wallet via this button failed._**

Image

_**Transaction on the EVM mainnet is hanging; encountered this error in the console.**_

Image

### Anything else?

_No response_

### LINKED ISSUE #2805: [BUG] Duplication & Incorrect Sort on the Validator Table on the Nomination Modal
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The validator table in the nomination modal appears to display duplicated rewards and does not allow sorting.

### Expected Behavior

The validator table should display correctly without duplication, and sorting should function properly, possibly with a default sort applied.

### Steps To Reproduce

1. Open the Tangle dApp locally and on the [development site](https://develop--tangle-dapp.netlify.app/).
2. Connect to an EVM wallet.
3. Select the `Nominate` tab in the sidebar.
4. Scroll to the `Nominations` table and click the `Nominate` button.
5. Enter the amount in the `Nomination` modal.
6. Click `Next` to view the validator table.
7. Interact with the table to identify the bug.

### Screenshot

https://github.com/user-attachments/assets/1b9d33a8-881b-435c-84cb-f15f33457909

Image

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yurixander**
## Summary of changes

_Provide a detailed description of proposed changes._

-

### Proposed area of change

_Put an `x` in the boxes that apply._

- [x] `apps/tangle-dapp`
- [ ] `apps/tangle-cloud`
- [ ] `libs/tangle-shared-ui`
- [ ] `libs/webb-ui-components`

### Associated issue(s)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2804
- Closes #2799
- Closes #2805

### Screen Recording

_If possible provide screenshots and/or a screen recording of proposed change._

Screenshot 2025-02-11 at 22 45 38
Screenshot 2025-02-11 at 22 46 17
Screenshot 2025-02-11 at 22 46 43
Screenshot 2025-02-11 at 22 47 08

### CODE REVIEW

**Comment by yurixander** [comment]
Status for this PR: Waiting on the batch precompile bug reproduction to determine if it is a Tangle node bug or a frontend/dapp problem. All the other issues in this PR have been addressed.

**Review by monaiuu — CHANGES_REQUESTED** [review]
while we're at it, can we fix inconsistent address formats:
Screenshot 2025-02-14 at 12 42 25 AM

File: libs/webb-ui-components/src/components/DropdownField/DropdownField.tsx
Comment (AtelyPham) [inline libs/webb-ui-components/src/components/DropdownField/DropdownField.tsx:1]: We can put this inside the `Dropdown` directory.

File: libs/webb-ui-components/src/components/Input/Input.tsx [hunk 1]
```diff
@@ -208,15 +208,14 @@ export const Input: React.FC<InputProps> = (props) => {
...
       {errorMessage !== undefined && (
         <Typography
           component="p"
           variant="body4"
           fw="bold"
           className="mt-2 text-red-70 dark:text-red-50"
-        >
-          {errorMessage}
-        </Typography>
+        ></Typography>
```
Comment (AtelyPham) [inline libs/webb-ui-components/src/components/Input/Input.tsx:218]:
```tsx
<Typography
  component="p"
  variant="body4"
  fw="bold"
  className="mt-2 text-red-70 dark:text-red-50"
>
	{errorMessage}
</Typography>
```

File: libs/webb-ui-components/src/components/Modal/ModalContent.tsx [hunk 2]
```diff
@@ -44,7 +44,7 @@ export const ModalContent = forwardRef<HTMLDivElement, ModalContentProps>(
           {...props}
           className={twMerge(
             // Prevent the focus border from showing.
-            'focus:outline-none',
+            'outline-none',
```
Comment (AtelyPham) [inline libs/webb-ui-components/src/components/Modal/ModalContent.tsx:47]:
```tsx
focus-visible:outline-none
```

I want to prevent this when the modal is focused by the keyboard.

CleanShot 2025-02-15 at 02 32 35@2x

**Review by AtelyPham — COMMENTED** [review]
Left some comments.

File: apps/tangle-dapp/src/components/TxHistoryDrawer.tsx [hunk 3]
```diff
@@ -0,0 +1,262 @@
...
+import { BN } from '@polkadot/util';
+import { TANGLE_TOKEN_DECIMALS } from '@webb-tools/dapp-config';
+import { capitalize } from 'lodash';
+import ExternalLink from './ExternalLink';
+import useAgnosticAccountInfo from '@webb-tools/tangle-shared-ui/hooks/useAgnosticAccountInfo';
+
+const TxHistoryDrawer = () => {
+  const activeAccountAddress = useActiveAccountAddress();
+  const transactions = useTxHistoryStore((state) => state.transactions);
+  const networkId = useNetworkStore((store) => store.network2?.id);
```
[the remark this answers is not in the document]
Comment (yurixander) [reply apps/tangle-dapp/src/components/TxHistoryDrawer.tsx:43]: @AtelyPham `network2` is the same as `network`, but with the difference that it is initially `undefined`. The idea is that it should be initially undefined, and when the initial network is determined, then it is set. Currently, it defaults to mainnet and then switches to whatever was last used, which causes some data-race style issues on PolkadotJS API. For now, this `network2` can be considered more of a "hotfix" until post-launch where I'll go more in-depth and replace all usage of `network` with `network2`.

**Review by AtelyPham — APPROVED** [review]
