### PR TITLE
fix(tangle-dapp): Fix token selector not working for Tangle mainnet

### LINKED ISSUE #2852: [BUG] Asset selection doesn't work on bridge
When Tangle mainnet or testnet is selected as the source chain on the bridge, the chosen asset from the asset dropdown is not being selected.

https://github.com/user-attachments/assets/74f0b08b-5a80-4e4d-9ff1-475eb5c0bd14

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Fixes #2852 

### Proposed area of change

- [x] `apps/tangle-dapp`
- [ ] `apps/tangle-cloud`
- [ ] `libs/tangle-shared-ui`
- [ ] `libs/ui-components`

### Associated issue(s)

- Closes #2852 

### Screen Recording

https://github.com/user-attachments/assets/15720ae6-d090-4569-8539-edce59fa6265

### CODE REVIEW

File: apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx [hunk 1]
```diff
@@ -426,18 +426,19 @@ const BridgeContainer = ({ className }: Props) => {
...
-              (tokenBalance: BridgeTokenWithBalance) =>
-                tokenBalance.address === token.address,
-            )?.syntheticBalance
-          : balances?.[sourceTypedChainId]?.find(
-              (tokenBalance: BridgeTokenWithBalance) =>
-                tokenBalance.address === token.address,
-            )?.balance;
+      const balance =
+        isNativeToken && token.tokenType === 'TNT'
+          ? formatEther(nativeTokenBalance?.value ?? BigInt(0))
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx:431]:
```
nativeTokenBalance?.value !== undefined
	? formatEther(nativeTokenBalance.value) 
	: undefined
```

File: apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx [hunk 2]
```diff
@@ -426,18 +426,19 @@ const BridgeContainer = ({ className }: Props) => {
 
   const assets: AssetConfig[] = useMemo(() => {
     return tokens.map((token) => {
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx:428]: Utilize AI to refactor this `assets` calculation memo for better readability and easier review.

**Review by AtelyPham — COMMENTED** [review]
Left some comments.

**Review by AtelyPham — APPROVED** [review]
