### PR TITLE
fix(tangle-dapp): Network Switching Improvements

### LINKED ISSUE #2825: [TASK] Network Switching Logic Inconsistencies and Improvements
## Description
Implement a network switcher component that handles different network states across various pages (dashboard, restaking, liquid staking, nomination, bridge) with appropriate network display and network switching capabilities. I have included a demo of the network switch behavior mocked up via Claude in this issue, please review to ensure implementation consistency. 

### Requirements
- The network switcher should adapt its display and behavior based on page context:
  - For pages (dashboard, restaking, etc) with only Tangle Network operational:
   - Display a clear switch prompt when user is on wrong network
   - Always display Tangle Network (mainnet or testnet)
- For bridge page with multiple networks operational:
  - Shows selected source chain (from) in top nav 
  - Selecting the network switcher in top nav opens up modal to switch chain (no dropdown)
  - Shows switch prompt if wallet network doesn't match source chain

### Key Points
- Top nav always reflects OPERATIONAL network for current page
  - For bridge, operational network = source chain
  - Network switch prompt appears in top nav when wallet doesn't match operational network

### Demo

https://claude.site/artifacts/299a41c8-c601-4e23-bb2d-797c8b89c282

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Fixes #2825 

### Proposed area of change

_Put an `x` in the boxes that apply._

- [x] `apps/tangle-dapp`
- [ ] `apps/tangle-cloud`
- [x] `libs/tangle-shared-ui`
- [ ] `libs/ui-components`

### Associated issue(s)

- Closes #2825 

### Screen Recording

https://github.com/user-attachments/assets/48b0dc5b-867c-4fdf-bd08-799ba9f12ba3

### CODE REVIEW

File: apps/tangle-dapp/src/context/bridge/useBridgeStore.ts [hunk 1]
```diff
@@ -111,11 +111,12 @@ const useBridgeStore = create<BridgeStore>((set) => ({
         ].supportedTokens;
 
       return {
-        selectedSourceChain: chain,
-        destinationChains: availableDestinations,
-        selectedDestinationChain: availableDestinations[0],
-        tokens,
-        selectedToken: tokens[0],
+        ...state,
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/context/bridge/useBridgeStore.ts:114]: We don't need the spread here; the setter returns an object that will be shallowly merged with the existing state in the store, read more [here](https://zustand.docs.pmnd.rs/guides/updating-state#flat-updates).

File: apps/tangle-dapp/src/context/bridge/useBridgeStore.ts [hunk 2]
```diff
@@ -111,11 +111,12 @@ const useBridgeStore = create<BridgeStore>((set) => ({
...
+        selectedSourceChain: { ...chain },
+        destinationChains: [...availableDestinations],
+        selectedDestinationChain: { ...availableDestinations[0] },
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/context/bridge/useBridgeStore.ts:117]: We need to verify whether the `availableDestinations` array is empty.

File: apps/tangle-dapp/src/context/bridge/useBridgeStore.ts [hunk 3]
```diff
@@ -111,11 +111,12 @@ const useBridgeStore = create<BridgeStore>((set) => ({
...
+        tokens: [...tokens],
+        selectedToken: { ...tokens[0] },
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/context/bridge/useBridgeStore.ts:119]: Same here, should check for empty array.

File: apps/tangle-dapp/src/containers/TopNavigationPanel.tsx [hunk 4]
```diff
@@ -1,16 +1,21 @@
...
-    <div className="flex items-center gap-2">
-      <NetworkSelectionButton />
+  const location = useLocation();
 
-      <ConnectWalletButton />
+  const isInBridgePath = location.pathname.startsWith(PagePath.BRIDGE);
 
+  return (
+    <div className="flex items-center gap-2">
+      {isInBridgePath ? <BridgeNetworkDisplay /> : <NetworkSelectorDropdown />}
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/TopNavigationPanel.tsx:17]: The `BridgeNetworkDisplay` and `NetworkSelectorDropdown` components exhibit significant code duplication in functionality, UI elements, and logic. We should unify them into a single component. You can provide the code for both components and ask AI to consolidate them.

File: apps/tangle-dapp/src/containers/TopNavigationPanel.tsx [hunk 5]
```diff
@@ -1,16 +1,21 @@
...
+      {isInBridgePath ? <BridgeConnectWallet /> : <ConnectWalletButton />}
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/TopNavigationPanel.tsx:18]: They should be unified into one component, as they are largely similar.

File: apps/tangle-dapp/src/containers/TopNavigationPanel.tsx (hunk 4 above)
Comment (devpavan04) [reply apps/tangle-dapp/src/containers/TopNavigationPanel.tsx:17]: @AtelyPham `NetworkSelectorDropdown` is a component in `tangle-shared-ui`. To unify this we would have to pass a bridge specific props to `NetworkSelectorDropdown`.

Comment (AtelyPham) [reply apps/tangle-dapp/src/containers/TopNavigationPanel.tsx:17]: Is it `selectedSourceChain`? Can we use it to determine the logic and pass that prop to the `NetworkSelectorDropdown`? This way, props can be passed to components for behavior customization, keeping them generalized rather than feature-specific. You can also ask AI to assist with this.

Comment (devpavan04) [reply apps/tangle-dapp/src/containers/TopNavigationPanel.tsx:17]: Yes, we need `selectedSourceChain` in `NetworkSelectorDropdown`. This is how it was previously implemented. We had a prop called `isBridgePath` on `NetworkSelectorDropdown`. We discussed not passing page-specific props (such as bridge, nomination, etc.) to components in `tangle-shared-ui`.

Comment (AtelyPham) [reply apps/tangle-dapp/src/containers/TopNavigationPanel.tsx:17]: We aren't passing page-specific props, but we can pass `isWrongEvmNetwork` and `switchToCorrectEvmChain`, which are not page-specific.

File: libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx [hunk 6]
```diff
@@ -17,16 +17,23 @@ import {
...
+type NetworkSelectionButtonProps = {
+  disableChainSelection?: boolean;
+  preferredChain?: ChainConfig;
+  overrideIsWrongEvmNetworkWithPreferredChain?: boolean;
+};
+
+const NetworkSelectionButton: FC<NetworkSelectionButtonProps> = ({
+  disableChainSelection = false,
+  preferredChain,
+  overrideIsWrongEvmNetworkWithPreferredChain = false,
```
Comment (AtelyPham) [inline libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx:35]: I believe `preferredChain` alone is sufficient to condition the component's behavior; this prop is unnecessary, in my opinion.

File: apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx [hunk 7]
```diff
@@ -735,7 +736,7 @@ export const BridgeConfirmationModal = ({
               chain={sourceChain}
               accAddress={activeAccountAddress}
               amount={feeDetails?.amounts.sending}
-              tokenName={token.tokenType}
+              tokenName={token?.tokenType || ''}
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx:739]: Shouldn't default to `''` here.

File: apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx [hunk 8]
```diff
@@ -745,7 +746,7 @@ export const BridgeConfirmationModal = ({
               chain={destinationChain}
               accAddress={destinationAddress}
               amount={feeDetails?.amounts.receiving}
-              tokenName={token.tokenType}
+              tokenName={token?.tokenType || ''}
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx:749]: Same here.

File: apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx [hunk 9]
```diff
@@ -254,22 +248,28 @@ const BridgeContainer = () => {
...
+      !selectedToken ||
+      !amount
+    ) {
       return null;
     }
 
     return {
       token: selectedToken,
-      amount: Number(amount?.toString() ?? '0'),
+      amount: Number(amount.toString()),
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx:272]: amount.toNumber()

File: apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx [hunk 10]
```diff
@@ -836,7 +827,7 @@ const BridgeContainer = () => {
                   placeholder="Enter amount to bridge"
                   wrapperClassName="dark:bg-mono-180"
                   showMaxAction
-                  decimals={selectedToken.decimals}
+                  decimals={selectedToken?.decimals ?? 18}
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx:830]: selectedToken?.decimals

Remove `?? 18` since there's already a default value for this prop.

File: apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx [hunk 11]
```diff
@@ -315,26 +318,29 @@ const BridgeContainer = () => {
...
       return null;
     }
 
-    const sendingAmount = parseFloat(
-      formatEther(BigInt(amount?.toString() ?? '0')),
-    );
+    const sendingAmount = parseFloat(formatEther(BigInt(amount.toString())));
 
     const formattedSendingAmount =
       sendingAmount.toString() + ' ' + routerQuote?.bridgeFee.symbol;
```
Comment (AtelyPham) [inline apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx:333]: Check for `undefined` values here to prevent displaying an undefined string in the UI.

**Review by AtelyPham — COMMENTED** [review]
Too many type casts here!  

Do you have a better way to do this? I think we have utility functions for converting and formatting display values; maybe you should try using them.

CleanShot 2025-03-03 at 02 43 36@2x

**Review by AtelyPham — APPROVED** [review]
As discussed, this [comment](https://github.com/tangle-network/dapp/pull/2855#pullrequestreview-2652799342) will be handled in a separate PR to ensure the PR size is not huge.

**Comment by drewstone** [comment]
Ok please fix the test CI too in separate PR.

Let's get it merged!
