### PR TITLE
fix(tangle-dapp): Network switching & other fixes

### LINKED ISSUE #2869: [BUG] Bridge dApp QA
- [x] Update promotional banner component font size, color and increase slider size.

Image

- [x] Update connect wallet modal copy.

Image

- [x] Change connection status colour to yellow here.

Image

- [x] Update copy here.

Image

- [x] Do not show Unknown Network here - it should default back to `network.name` from `useNetworkStore`.

Image

- [x] Do not default to the first chain from the source chain list.

Image

Image

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Update the promotional banner component's font size, color and increase slider size.
- Update the `Connect Wallet` modal's default copy.
- Change the connection status color to yellow if selected but not connected.
- Update the copy from `Wrong EVM chain connected` to `Switch to the selected network`.
- Set the Tangle chain as the default source chain on the Bridge.

### Proposed area of change

- [x] `apps/tangle-dapp`
- [ ] `apps/tangle-cloud`
- [x] `libs/tangle-shared-ui`
- [ ] `libs/ui-components`

### Associated issue(s)

- Closes #2869 

### Screen Recording & Screenshots

https://github.com/user-attachments/assets/14c3e735-a3f5-4f0d-880c-b686b643fa3b

CleanShot 2025-03-04 at 14 06 32@2x

https://github.com/user-attachments/assets/41b5ff65-edd7-4159-b5e6-34cd88c5b33d

### CODE REVIEW

File: libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx [hunk 1]
```diff
@@ -56,16 +56,14 @@ const NetworkSelectionButton: FC<NetworkSelectionButtonProps> = ({
...
-              'Unknown Network');
+          : (activeChain?.displayName ?? activeChain?.name ?? network?.name);
       }
 
       return (
         network?.name ??
         activeChain?.displayName ??
         activeChain?.name ??
-        'Unknown Network'
+        network?.name
```
Comment (yurixander) [inline libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx:66]: Will it show up as `undefined` if all options are not available?

File: libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx [hunk 2]
```diff
@@ -138,7 +136,7 @@ const NetworkSelectionButton: FC<NetworkSelectionButtonProps> = ({
             </div>
           </TooltipTrigger>
 
-          <TooltipBody>Wrong EVM Chain Connected</TooltipBody>
+          <TooltipBody>Switch to Selected Network</TooltipBody>
```
Comment (yurixander) [inline libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx:139]:
```suggestion
          <TooltipBody>Switch to Selected EVM Network</TooltipBody>
```

**Review by AtelyPham — APPROVED** [review]
